name: lint and test
on: [push,workflow_dispatch]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout code 
                uses: actions/checkout@v3
            -   name: Install node
                uses: actions/setup-node@v3
                with:
                    node-version: 18
            -   name: Install dependencies 
                run: npm ci
            -   name: Run tests
                run: npm tests
    lint:
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout code 
                uses: actions/checkout@v3
            -   name: Install node
                uses: actions/setup-node@v3
                with:
                    node-version: 18
            -   name: Install dependencies 
                run: npm ci
            -   name: lint command
                run: eslint --ext .jsx --fix src
    preview:
        needs: build 
        runs-on: ubuntu-latest
        steps: 
            -   name: preview
                run: vite preview
