name: Lint flow 
on: [push]
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout code 
                uses: actions/checkout@3
            -   name: Install node
                uses: actions/setup-node@v3
                with:
                    node-version: 18
            -   name: Install dependencies 
                run: npm ci
            -   name: Run tests
                run: npm tests